#ifndef __CONFIG_COMPAT_H__
#define __CONFIG_COMPAT_H__

#include <linux/autoconf.h>

#undef CONFIG_VIDEO_BWQCAM
#undef CONFIG_VIDEO_SAA7146
#undef CONFIG_DVB_TDA826X
#undef CONFIG_VIDEO_SAA7146_VV
#undef CONFIG_VIDEO_DPC
#undef CONFIG_DVB_TTUSB_BUDGET
#undef CONFIG_VIDEO_EM28XX
#undef CONFIG_VIDEO_CX88_VP3054
#undef CONFIG_DVB_CINERGYT2
#undef CONFIG_VIDEO_WM8775
#undef CONFIG_DVB_USB_DIGITV
#undef CONFIG_DVB_MANTIS
#define CONFIG_DVB_MANTIS_MODULE 1
#undef CONFIG_VIDEO_CPIA_USB
#undef CONFIG_VIDEO_BT848
#undef CONFIG_VIDEO_USBVIDEO
#undef CONFIG_DVB_TTUSB_DEC
#undef CONFIG_DVB_SP8870
#define CONFIG_DVB_SP8870_MODULE 1
#undef CONFIG_USB_OV511
#undef CONFIG_VIDEO_PVRUSB2_24XXX
#undef CONFIG_RADIO_MAESTRO
#undef CONFIG_DVB_S5H1420
#undef CONFIG_RADIO_MIROPCM20
#undef CONFIG_DVB_NXT200X
#undef CONFIG_DVB_TDA10021
#undef CONFIG_DVB_CORE
#define CONFIG_DVB_CORE_MODULE 1
#undef CONFIG_VIDEO_PVRUSB2_SYSFS
#undef CONFIG_DVB_CORE_ATTACH
#undef CONFIG_USB_SN9C102
#undef CONFIG_VIDEO_UPD64083
#undef CONFIG_USB_DABUSB
#undef CONFIG_DVB_DIB3000MC
#undef CONFIG_DVB_PLUTO2
#undef CONFIG_RADIO_GEMTEK_PCI
#undef CONFIG_DVB_TDA1004X
#undef CONFIG_VIDEO_SAA711X
#undef CONFIG_DVB_BT8XX
#undef CONFIG_VIDEO_CQCAM
#undef CONFIG_VIDEO_ZORAN_AVS6EYES
#undef CONFIG_TUNER_3036
#undef CONFIG_USB_SE401
#undef CONFIG_DVB_L64781
#undef CONFIG_VIDEO_BUF_DVB
#define CONFIG_VIDEO_BUF_DVB_MODULE 1
#undef CONFIG_DVB_USB_DTT200U
#undef CONFIG_RADIO_TRUST
#undef CONFIG_VIDEO_HEXIUM_ORION
#undef CONFIG_VIDEO_V4L1_COMPAT
#define CONFIG_VIDEO_V4L1_COMPAT 1
#undef CONFIG_VIDEO_CX88_ALSA
#undef CONFIG_DVB_TUNER_MT2060
#undef CONFIG_DVB_SP887X
#define CONFIG_DVB_SP887X_MODULE 1
#undef CONFIG_DVB_STV0297
#undef CONFIG_DVB_CX22700
#define CONFIG_DVB_CX22700_MODULE 1
#undef CONFIG_VIDEO_SAA7134
#undef CONFIG_VIDEO_WM8739
#undef CONFIG_DVB_PLL
#define CONFIG_DVB_PLL_MODULE 1
#undef CONFIG_VIDEO_VIDEOBUF
#undef CONFIG_DVB_MT352
#define CONFIG_DVB_MT352_MODULE 1
#undef CONFIG_USB_VICAM
#undef CONFIG_USB_STV680
#undef CONFIG_VIDEO_MSP3400
#define CONFIG_VIDEO_MSP3400_MODULE 1
#undef CONFIG_VIDEO_SAA5249
#undef CONFIG_DVB_USB_GP8PSK
#undef CONFIG_VIDEO_STRADIS
#undef CONFIG_VIDEO_ZORAN_DC10
#undef CONFIG_DVB_MT312
#undef CONFIG_VIDEO_TUNER
#define CONFIG_VIDEO_TUNER_MODULE 1
#undef CONFIG_VIDEO_PLANB
#undef CONFIG_VIDEO_ADV_DEBUG
#undef CONFIG_VIDEO_ZORAN_LML33R10
#undef CONFIG_DVB_B2C2_FLEXCOP_DEBUG
#undef CONFIG_VIDEO_CX88_BLACKBIRD
#undef CONFIG_VIDEO_V4L2
#define CONFIG_VIDEO_V4L2 1
#undef CONFIG_VIDEO_PMS
#undef CONFIG_DVB_USB_DIBUSB_MB_FAULTY
#undef CONFIG_DVB_CX22702
#define CONFIG_DVB_CX22702_MODULE 1
#undef CONFIG_VIDEO_MEYE
#undef CONFIG_VIDEO_HEXIUM_GEMINI
#undef CONFIG_VIDEO_CX2341X
#undef CONFIG_RADIO_MAXIRADIO
#undef CONFIG_RADIO_AZTECH
#undef CONFIG_DVB_ISL6421
#define CONFIG_DVB_ISL6421_MODULE 1
#undef CONFIG_DVB_OR51211
#define CONFIG_DVB_OR51211_MODULE 1
#undef CONFIG_DVB_NXT6000
#define CONFIG_DVB_NXT6000_MODULE 1
#undef CONFIG_DVB_STB0899
#define CONFIG_DVB_STB0899_MODULE 1
#undef CONFIG_DVB_USB_NOVA_T_USB2
#undef CONFIG_USB_IBMCAM
#undef CONFIG_DVB_LNBP21
#undef CONFIG_USB_ZC0301
#undef CONFIG_DVB_MANTIS_CI
#define CONFIG_DVB_MANTIS_CI_MODULE 1
#undef CONFIG_DVB_USB_VP702X
#undef CONFIG_VIDEO_SAA7127
#undef CONFIG_DVB_ZL10353
#define CONFIG_DVB_ZL10353_MODULE 1
#undef CONFIG_VIDEO_SAA7134_ALSA
#undef CONFIG_DVB_B2C2_FLEXCOP_USB
#undef CONFIG_DVB_BUDGET_PATCH
#undef CONFIG_DVB_CINERGYT2_ENABLE_RC_INPUT_DEVICE
#undef CONFIG_DVB_BUDGET
#undef CONFIG_DVB_VES1820
#undef CONFIG_VIDEO_CX88_DVB
#define CONFIG_VIDEO_CX88_DVB_MODULE 1
#undef CONFIG_DVB_BCM3510
#undef CONFIG_DVB_AV7110_FIRMWARE
#undef CONFIG_VIDEO_CS53L32A
#undef CONFIG_DVB_TDA8083
#undef CONFIG_DVB_FE_CUSTOMISE
#define CONFIG_DVB_FE_CUSTOMISE 1
#undef CONFIG_VIDEO_ZORAN_LML33
#undef CONFIG_USB_DSBR
#undef CONFIG_VIDEO_SAA7134_DVB
#undef CONFIG_USB_ET61X251
#undef CONFIG_DVB_B2C2_FLEXCOP
#undef CONFIG_USB_KONICAWC
#undef CONFIG_RADIO_CADET
#undef CONFIG_VIDEO_W9966
#undef CONFIG_USB_W9968CF
#undef CONFIG_VIDEO_IR
#define CONFIG_VIDEO_IR_MODULE 1
#undef CONFIG_VIDEO_M32R_AR
#undef CONFIG_DVB_USB_DEBUG
#undef CONFIG_DVB_CX24110
#define CONFIG_DVB_CX24110_MODULE 1
#undef CONFIG_DVB_MB86A16
#define CONFIG_DVB_MB86A16_MODULE 1
#undef CONFIG_DVB_BUDGET_CI
#undef CONFIG_DVB_STV0299
#define CONFIG_DVB_STV0299_MODULE 1
#undef CONFIG_DVB_CINERGYT2_TUNING
#undef CONFIG_VIDEO_CPIA2
#undef CONFIG_VIDEO_OVCAMCHIP
#undef CONFIG_DVB_CU1216
#define CONFIG_DVB_CU1216_MODULE 1
#undef CONFIG_VIDEO_VIVI
#undef CONFIG_RADIO_GEMTEK
#undef CONFIG_RADIO_SF16FMI
#undef CONFIG_DVB_BUDGET_AV
#undef CONFIG_DVB_AV7110
#undef CONFIG_DVB_B2C2_FLEXCOP_PCI
#undef CONFIG_RADIO_SF16FMR2
#undef CONFIG_DVB_USB
#undef CONFIG_VIDEO_VINO
#undef CONFIG_DVB_OR51132
#define CONFIG_DVB_OR51132_MODULE 1
#undef CONFIG_VIDEO_KERNEL_VERSION
#define CONFIG_VIDEO_KERNEL_VERSION 1
#undef CONFIG_DVB_USB_UMT_010
#undef CONFIG_VIDEO_TVEEPROM
#define CONFIG_VIDEO_TVEEPROM_MODULE 1
#undef CONFIG_RADIO_TERRATEC
#undef CONFIG_RADIO_ZOLTRIX
#undef CONFIG_RADIO_MIROPCM20_RDS
#undef CONFIG_VIDEO_ZORAN
#undef CONFIG_VIDEO_CX88
#define CONFIG_VIDEO_CX88_MODULE 1
#undef CONFIG_RADIO_RTRACK2
#undef CONFIG_USB_QUICKCAM_MESSENGER
#undef CONFIG_DVB_USB_DIBUSB_MC
#undef CONFIG_RADIO_TYPHOON_PROC_FS
#undef CONFIG_DVB_DIB3000MB
#undef CONFIG_DVB_USB_VP7045
#undef CONFIG_VIDEO_V4L1
#define CONFIG_VIDEO_V4L1 1
#undef CONFIG_DVB_USB_CXUSB
#undef CONFIG_VIDEO_BTCX
#define CONFIG_VIDEO_BTCX_MODULE 1
#undef CONFIG_VIDEO_ZR36120
#undef CONFIG_VIDEO_TLV320AIC23B
#undef CONFIG_VIDEO_CPIA_PP
#undef CONFIG_USB_PWC_DEBUG
#undef CONFIG_DVB_USB_A800
#undef CONFIG_DVB
#define CONFIG_DVB 1
#undef CONFIG_VIDEO_CPIA
#undef CONFIG_DVB_USB_DIBUSB_MB
#undef CONFIG_VIDEO_BUF
#define CONFIG_VIDEO_BUF_MODULE 1
#undef CONFIG_VIDEO_BT848_DVB
#undef CONFIG_VIDEO_SAA6588
#undef CONFIG_DVB_CX24123
#define CONFIG_DVB_CX24123_MODULE 1
#undef CONFIG_RADIO_TYPHOON
#undef CONFIG_VIDEO_DEV
#define CONFIG_VIDEO_DEV_MODULE 1
#undef CONFIG_USB_PWC
#undef CONFIG_DVB_VES1X93
#undef CONFIG_VIDEO_UPD64031A
#undef CONFIG_VIDEO_SAA7134_OSS
#undef CONFIG_DVB_LGDT330X
#undef CONFIG_VIDEO_ZORAN_BUZ
#undef CONFIG_DVB_AV7110_OSD
#undef CONFIG_VIDEO_PVRUSB2_DEBUGIFC
#undef CONFIG_VIDEO_M32R_AR_M64278
#undef CONFIG_VIDEO_ZORAN_DC30
#undef CONFIG_VIDEO_MXB
#undef CONFIG_VIDEO_SAA5246A
#undef CONFIG_VIDEO_CX25840
#undef CONFIG_VIDEO_PVRUSB2
#undef CONFIG_RADIO_RTRACK
#undef CONFIG_DVB_TDA10086

#endif
