# Makefile for linuxtv.org dvb-apps/util/switch

objects  = switch.o

binaries = switch

inst_bin = $(binaries)

CPPFLAGS += -I../../include

.PHONY: all

all: $(binaries)

$(binaries): $(objects)

include ../../Make.rules
